language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "MRXmwbkpR8984IFG4B6mPBTqjhcpBSiz9Mg1/ujsoHfW4kfI4Jt8gtlbD3gYqTIB4Xx0r5Hdh3FpWlwgnUWE6NIhDdG8iXq4i30WfaJijVzpkLgHboQyguMjlQ51K6YttqqaQkQV4Z+t3l56N79yt8E3qI5DqKfYyoyrVb62k/kz/MFa2PsMDppjeblqBqnfSIBQKAIxGEXE5QydkOTTKHfC1sPOwg3hMEcCD3m4Cv2tN6P35B9yni2DxlMjaYE0fPNnK4O3rjhYSDqpuzJa2cZ60TZYxxHamV4EV1pFySXNdINGITSA7tp2+iCL1240MJlSmGpTqYcno+cXe8dT6orEBMQ2V0aqkT3pu+pDwTQFweS/L9+/HA89VUxKy7KiqlxIQ2ICGZaOYIpV6p1lOmZV5Pc1MuAqaliMSaY4fODlh3wwo3djEtuAEq1SVWWGA80W6idb3Em7EF5KSQu7SwJk3H+YSk9nS4Yx2e6i9CR1X03oRvr3qouIXvHP74rta1KxDqggt3pzVhU1tKLQAtKFOdAaGU7dE/PLELZwUHqo1oE+AIhmK8OAs6DwbObiFkiED7dgENzDiAucbfdLf/18LP1jTX00cLVBadaqt3+uxGoI8kpE2STBCDIdrTKxw46n7XTqOYVri5UkxIkIa7oK2JnUz9/iWgbYwFVzvG0="
env:
  secure: "mXvIIGyTXeBadQH6BW1j05aHnWEkRMJjhDMlRHLY2dRwI28SgdXLB1i8JMJY4zmrGvVjT5T7DbUj0DdyiiMyuhPR5ZI2O/z78NqD29qIwe/NfxFTwHxvELRuJFErH+nGbc1eoV5iK5sPGQVPS96ycPze3vQD1o8vIb2JYIjhbEYwgNV4E97sUWlAJ30hlNabai4sAHBQ6zAr8OgpBPnFqple6JpqoBhL8upG48SbGtY4t0MAcfG0u93ve/bbg224XITf1X8EG2b04y6QX4Xx3Rr+CuaAx7VZV/KZXC82b/Chb2NT8nCrvSSnM2mfvJkJiYtYJ00RsXP+awCt5Hpx7Fnk7i0qI/9101KFSiSZ4TlYzlYcTZMkbtJNoMQL+7fuDfSqZsOadC/iIt+UdZVV2MVZXzEyxcXmKOtt6MlHY4MNIZj+PnMtmghR7goRU8IIHsLQ3krLokdxNOg6Ly6/aeWrz01Ya69qfTBU8RGnx/gNuIf9gegtvsxR3OcmCTl7huUsSre2O43fJ2ntKhGGRe6dR/jf12f0LYai/14to/GpBRSylq0taf8OLfE/1gHRGSAQQo8ce8LmYL0CTXU6Jc1bz0mcDhC0XFRT+qTjKDI2AKa5IKeMHfWXNtP+JXIUaJs2a+xE9hKsk+cFAX7S4qCIUrhwlA29KgIlLeveL4w="
