language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "MRXmwbkpR8984IFG4B6mPBTqjhcpBSiz9Mg1/ujsoHfW4kfI4Jt8gtlbD3gYqTIB4Xx0r5Hdh3FpWlwgnUWE6NIhDdG8iXq4i30WfaJijVzpkLgHboQyguMjlQ51K6YttqqaQkQV4Z+t3l56N79yt8E3qI5DqKfYyoyrVb62k/kz/MFa2PsMDppjeblqBqnfSIBQKAIxGEXE5QydkOTTKHfC1sPOwg3hMEcCD3m4Cv2tN6P35B9yni2DxlMjaYE0fPNnK4O3rjhYSDqpuzJa2cZ60TZYxxHamV4EV1pFySXNdINGITSA7tp2+iCL1240MJlSmGpTqYcno+cXe8dT6orEBMQ2V0aqkT3pu+pDwTQFweS/L9+/HA89VUxKy7KiqlxIQ2ICGZaOYIpV6p1lOmZV5Pc1MuAqaliMSaY4fODlh3wwo3djEtuAEq1SVWWGA80W6idb3Em7EF5KSQu7SwJk3H+YSk9nS4Yx2e6i9CR1X03oRvr3qouIXvHP74rta1KxDqggt3pzVhU1tKLQAtKFOdAaGU7dE/PLELZwUHqo1oE+AIhmK8OAs6DwbObiFkiED7dgENzDiAucbfdLf/18LP1jTX00cLVBadaqt3+uxGoI8kpE2STBCDIdrTKxw46n7XTqOYVri5UkxIkIa7oK2JnUz9/iWgbYwFVzvG0="
